"""options table

Revision ID: 84489dca2a60
Revises: a28908e9e6f5
Create Date: 2019-11-15 16:30:27.735266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84489dca2a60'
down_revision = 'a28908e9e6f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=240), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_option')
    # ### end Alembic commands ###
