"""options table ix

Revision ID: 8af57a53dc4e
Revises: c2640a5c2ded
Create Date: 2019-11-15 16:59:04.550690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8af57a53dc4e'
down_revision = 'c2640a5c2ded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=240), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_option_chat_key', 'chat_option', ['chat_id', 'key'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_option_chat_key', table_name='chat_option')
    op.drop_table('chat_option')
    # ### end Alembic commands ###
