"""photo model structure

Revision ID: 9648d6ae999d
Revises: e42c76e8aa8e
Create Date: 2019-11-15 21:48:15.516972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9648d6ae999d'
down_revision = 'e42c76e8aa8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yd_filename', sa.String(length=240), nullable=False))
        batch_op.add_column(sa.Column('yd_sub_folder', sa.String(length=240), nullable=False))
        batch_op.drop_column('yd_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yd_path', sa.VARCHAR(length=240), nullable=False))
        batch_op.drop_column('yd_sub_folder')
        batch_op.drop_column('yd_filename')

    # ### end Alembic commands ###
