"""options table constraint

Revision ID: 9aae2b250a3d
Revises: b531c6dadfcf
Create Date: 2019-11-15 17:28:47.955132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aae2b250a3d'
down_revision = 'b531c6dadfcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('local_folder', sa.String(length=240), nullable=False),
    sa.Column('yd_folder', sa.String(length=240), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=240), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('msg_date', sa.DateTime(), nullable=False),
    sa.Column('msg_id', sa.Integer(), nullable=False),
    sa.Column('yd_path', sa.String(length=240), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_hash', 'photo', ['chat_id', 'file_hash'], unique=False)
    op.create_index('ix_user_hash_date', 'photo', ['user_id', 'file_hash', 'msg_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_hash_date', table_name='photo')
    op.drop_index('ix_chat_hash', table_name='photo')
    op.drop_table('photo')
    op.drop_table('chat')
    # ### end Alembic commands ###
