"""options table constraint

Revision ID: a336639792e2
Revises: 9aae2b250a3d
Create Date: 2019-11-15 17:46:00.776607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a336639792e2'
down_revision = '9aae2b250a3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=240), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'key', name='uc_chat_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_option')
    # ### end Alembic commands ###
