"""options table constraint

Revision ID: b531c6dadfcf
Revises: 8af57a53dc4e
Create Date: 2019-11-15 17:22:40.911136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b531c6dadfcf'
down_revision = '8af57a53dc4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat')
    op.drop_index('ix_option_chat_key', table_name='chat_option')
    op.drop_table('chat_option')
    op.drop_index('ix_chat_hash', table_name='photo')
    op.drop_index('ix_user_hash_date', table_name='photo')
    op.drop_table('photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('file_hash', sa.VARCHAR(length=240), nullable=False),
    sa.Column('chat_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('msg_date', sa.DATETIME(), nullable=False),
    sa.Column('msg_id', sa.INTEGER(), nullable=False),
    sa.Column('yd_path', sa.VARCHAR(length=240), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_hash_date', 'photo', ['user_id', 'file_hash', 'msg_date'], unique=False)
    op.create_index('ix_chat_hash', 'photo', ['chat_id', 'file_hash'], unique=False)
    op.create_table('chat_option',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chat_id', sa.INTEGER(), nullable=True),
    sa.Column('key', sa.VARCHAR(length=50), nullable=False),
    sa.Column('value', sa.VARCHAR(length=240), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_option_chat_key', 'chat_option', ['chat_id', 'key'], unique=False)
    op.create_table('chat',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=240), nullable=False),
    sa.Column('local_folder', sa.VARCHAR(length=240), nullable=False),
    sa.Column('yd_folder', sa.VARCHAR(length=240), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
